ticker: MU
tickers:
- MU
- SPY_S&P500
- NVDA
- QQQ
- TSLA
- AMD
- INTC
- AAPL
- MSFT
- GOOGL
- AMZN
- META
- SOXL
- AVGO
- GOOG
- IWM
- QCOM
- LITE
- PLTR
- SMH
- TSM
- TQQQ
- MRVL
- SOXX
- VOO
- WDC
- IVV
- ORCL
- STX
- LLY
- RKLB
- AMAT
- EWY
- LQD
- IREN
- CSCO
- NFLX
- HYG
- BE
- SOXS
- GLW
- XOM
- MSTR
- NOW
- SQQQ
- LRCX
- ASML
- WMT
- APP
- V
- GLD
- UNH
- JPM
- CAT
- COHR
- BRK.B
- DIA
- TLT
- CRM
- TXN
- AAOI
- XLE
- COST
- SGOV
- ANET
- XLK
- RSP
- ASTS
- COIN
- KLAC
- VRT
- IBM
- IONQ
- CVX
- IGV
- MA
- EEM
- GDX
- GS
- PANW
- BABA
- DELL
- HOOD
- XLF
- CRWD
- NOK
- SLV
- JNJ
- HD
- BAC
- INTU
- ADI
- SHOP
- APH
- BA
- GE
- 'ON'
- EFA
- UBER
- C
start_date: '2021-05-28'
eval_start_date: '2025-01-02'
end_date: '2026-05-27'
context_length: 512
forecast_horizon: 5
target_column: close
output_dir: outputs/kronos_dataset_top100/base_context512_stride21_s3
batch_size: 16
eval_stride: 21
model_id: NeoQuasar/Kronos-base
tokenizer_id: NeoQuasar/Kronos-Tokenizer-base
kronos_cache_dir: null
device: auto
temperature: 0.6
top_k: 0
top_p: 0.9
sample_count: 3
clip: 5.0
random_seed: 42
use_adjusted_ohlc: false
data_source: local_kronos_csv
local_data_dir: dataset/data/kronos/combined_by_ticker
